spring.application.name=inventory-service

#api-props
server.servlet.context-path=/api/v1

# db-properties

spring.datasource.url=jdbc:postgresql://localhost:5432/supermaarkt?currentSchema=app
spring.datasource.username=maarkt_admin
spring.datasource.password=Postgressan@8
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
